// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7AplzmK7_BnQ4mjeOLT-3rPeTD9WiUPA',
    appId: '1:267749204384:web:35ecdd7feeace1ad2bc4c5',
    messagingSenderId: '267749204384',
    projectId: 'smart-restaurant-pos',
    authDomain: 'smart-restaurant-pos.firebaseapp.com',
    databaseURL: 'https://smart-restaurant-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-restaurant-pos.firebasestorage.app',
    measurementId: 'G-NQL89X0FL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmS4M4fWXj98gfm2m7Le3TuzUMwsN7eVM',
    appId: '1:267749204384:android:f7702bcb03944ee62bc4c5',
    messagingSenderId: '267749204384',
    projectId: 'smart-restaurant-pos',
    databaseURL: 'https://smart-restaurant-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-restaurant-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdcNffAXe1jnoBjp3TaJYJkzmP1bFlrms',
    appId: '1:267749204384:ios:043f184506e9c7f72bc4c5',
    messagingSenderId: '267749204384',
    projectId: 'smart-restaurant-pos',
    databaseURL: 'https://smart-restaurant-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-restaurant-pos.firebasestorage.app',
    iosBundleId: 'com.example.smartRestupos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdcNffAXe1jnoBjp3TaJYJkzmP1bFlrms',
    appId: '1:267749204384:ios:043f184506e9c7f72bc4c5',
    messagingSenderId: '267749204384',
    projectId: 'smart-restaurant-pos',
    databaseURL: 'https://smart-restaurant-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-restaurant-pos.firebasestorage.app',
    iosBundleId: 'com.example.smartRestupos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7AplzmK7_BnQ4mjeOLT-3rPeTD9WiUPA',
    appId: '1:267749204384:web:6542008ab796f96b2bc4c5',
    messagingSenderId: '267749204384',
    projectId: 'smart-restaurant-pos',
    authDomain: 'smart-restaurant-pos.firebaseapp.com',
    databaseURL: 'https://smart-restaurant-pos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-restaurant-pos.firebasestorage.app',
    measurementId: 'G-HRFFSTB6N5',
  );
}
